#!/bin/bash


counter=1
while [ $counter -le 2 ]
do
  ./target/debug/spl-token-metadata-test-client --keypair ~/merc_minter_wallet.json mint_new_edition_from_master_edition_via_token --mint 2LQS4NDJdUPfPFAbXz9Ejgo1CFUN2R43jQhfhKKHbmxR --url https://api.metaplex.solana.com/
  ((counter++))
done

echo All done
