#!/bin/bash


counter=1
while [ $counter -le 1 ]
do
  ./target/debug/spl-token-metadata-test-client --keypair ~/phantom_wallet.json mint_new_edition_from_master_edition_via_token --mint BSwtycr8WJJ79iftM2A4Bb9aA9xhorZysv6j7tXJY1Tv --url https://api.metaplex.solana.com/
  ((counter++))
done

echo All done
